# Generated by Django 4.2.13 on 2024-05-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NoteUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=15)),
                ("password", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=30)),
                ("phone_number", models.CharField(max_length=20)),
                ("signature", models.CharField(max_length=40)),
            ],
        ),
    ]
