# Generated by Django 4.2.13 on 2024-05-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="noteuser",
            name="avatar",
            field=models.ImageField(
                default="images/images/default.png", upload_to="images/images/"
            ),
        ),
        migrations.AlterField(
            model_name="noteuser",
            name="email",
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="noteuser",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="noteuser",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="noteuser",
            name="signature",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="noteuser",
            name="username",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
