# Generated by Django 4.2.13 on 2024-05-29 02:27

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_noteuser_avatar_alter_noteuser_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noteuser",
            name="avatar",
            field=models.ImageField(
                default="images/avatars/default.png",
                upload_to=user.models.PathAndRename("images/avatars/"),
            ),
        ),
        migrations.AlterField(
            model_name="noteuser",
            name="email",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="noteuser",
            name="password",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="noteuser",
            name="signature",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="noteuser",
            name="username",
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
