# Generated by Django 4.1 on 2024-06-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("note", "0003_note_emotion_note_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="image_url",
            field=models.URLField(default=""),
        ),
    ]
