# Generated by Django 4.2.13 on 2024-06-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("note", "0004_alter_note_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="title",
            field=models.CharField(default="", max_length=50),
        ),
    ]
